# GPU 클러스터 인벤토리 파일
# 실제 환경에 맞게 IP 주소와 호스트명을 수정하세요

all:
  vars:
    # 모든 호스트에 적용되는 SSH 설정
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Control Node: Prometheus, Grafana, Alertmanager가 설치될 서버
    control:
      hosts:
        control-node:
          ansible_host: 192.168.1.100
          # ansible_user: admin  # 다른 사용자 사용 시

    # GPU Nodes: Node Exporter, DCGM Exporter가 설치될 서버들
    gpu_nodes:
      hosts:
        gpu-node-01:
          ansible_host: 192.168.1.101
          gpu_count: 8
          gpu_type: a100
        gpu-node-02:
          ansible_host: 192.168.1.102
          gpu_count: 8
          gpu_type: a100
        gpu-node-03:
          ansible_host: 192.168.1.103
          gpu_count: 8
          gpu_type: a100
        # 추가 노드는 아래 형식으로 추가
        # gpu-node-04:
        #   ansible_host: 192.168.1.104
        #   gpu_count: 8
        #   gpu_type: h100

    # 모든 노드 (node_exporter 설치 대상)
    all_nodes:
      children:
        control:
        gpu_nodes:
